site_name: Scripts
site_description: Some scripts for the SMByC project
site_author: Xavier Corredor Llano, SMBYC-IDEAM
#site_favicon: favicon_whale.png
site_url: https://smbyc.bitbucket.io/scripts
repo_url: https://bitbucket.org/smbyc/scripts
theme: mkdocs
extra_css:
    - css/extra.css
markdown_extensions:
  - smarty
  - admonition
  - toc:
      permalink: true
pages:
- Home: index.md
- Installation: installation.md
- Scripts: scripts.md
